config/routes.rb
Rails.application.routes.draw do
  
   root 'static_pages#home'
  resources :orders
  get 'store/index', as: 'destination'
  resources :store
  
    get 'carts/current' => 'carts#current', as: 'current'

  resources :line_items
  resources :carts
  resources :tours
 
  get   'about'   => 'static_pages#about'

  get   'contact' => 'static_pages#contact'

  get   'term'    => 'static_pages#term'

  get    'team'   => 'static_pages#team'

  get 'sessions/new'
 resources :users
    get     'signup' => 'users#new'
    get     'login'  => 'sessions#new'
    post    'login'   => 'sessions#create'
    get    'logout'  => 'sessions#destroy'
    get   'profile'  => 'users#show'
   

end

app/models/tour.rb
class Tour < ActiveRecord::Base
    belongs_to :order
    has_many :line_items
    before_destroy :ensure_not_referenced_by_any_line_item
    
def self.search(query)
    where("title like ?", "%#{query}%")
    where("location like ?", "%#{query}%")
end 
 
    private
    
# ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
        if line_items.empty?
         return true
    else
        errors.add(:base, 'Line Items present')
        return false
        end
    end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  # GET /tours
  # GET /tours.json
def index
    if params[:search]
      @tours = Tour.search(params[:search]).order("created_at DESC")
    else
      @tours = Tour.order("created_at DESC")
    end
end

def show
end

  # GET /tours/new
def new
    @tour = Tour.new
end

  # GET /tours/1/edit
def edit
end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)
    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
def who_bought
    @tour = tour.find(params[:id])
    respond_to do |format|
    format.atom
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:title, :description, :image_url, :location, :duration, :season, :level, :tour_type, :Price)
    end
end
end

app/helpers/tours_helper.rb
module ToursHelper
    
    def current_tour
    @current_tour = Tour.find(params[:tour_id])
    end 
end

app/views/tours/_form.html.erb
<%= form_for(@tour) do |f| %>
  <% if @tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% @tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :row => 20 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :season %><br>
    <%= f.text_field :season %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="field">
    <%= f.label :tour_type %><br>
    <%= f.text_field :tour_type %>
  </div>
  <div class="field">
    <%= f.label :Price %><br>
    <%= f.text_field :Price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tours/edit.html.erb
<h1>Editing Tour</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>


<h1>Start the Adventure</h1>
	<p>Pick your favorite place to start the Adventure</p>
	
 <% @tours.each do |tour| %>
  <div class="entry">
    <%= image_tag(tour.image_url) %>
        <h3><%= tour.title %></h3>
            <%= sanitize(tour.description) %>
    <div class="price_line">
        <span class="price"><%= number_to_currency(tour.Price) %></span>
            <%= button_to 'Add to Cart', line_items_path(tour_id: tour)%>
    </div>
  </div>
<% end %>

<h1>Loook all our tours</h1>
	
	<%= link_to "destination", destination_path %>

app/views/tours/new.html.erb
<h1>New Tour</h1>

<%= render 'form' %>

<%= link_to 'Back', tours_path %>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> title:</strong>
  <%= @tour. title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tour.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @tour.image_url %>
</p>

<p>
  <strong>Location:</strong>
  <%= @tour.location %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @tour.duration %>
</p>

<p>
  <strong>Season:</strong>
  <%= @tour.season %>
</p>

<p>
  <strong>Level:</strong>
  <%= @tour.level %>
</p>

<p>
  <strong>Tour type:</strong>
  <%= @tour.tour_type %>
</p>

<p>
  <strong>Price:</strong>
  <%= @tour.Price %>
</p>

<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>