config/routes.rb
Rails.application.routes.draw do
  
   root 'static_pages#home'
  resources :orders
  get 'store/index', as: 'destination'
  resources :store
  
    get 'carts/current' => 'carts#current', as: 'current'

  resources :line_items
  resources :carts
  resources :tours
 
  get   'about'   => 'static_pages#about'

  get   'contact' => 'static_pages#contact'

  get   'term'    => 'static_pages#term'

  get    'team'   => 'static_pages#team'

  get 'sessions/new'
 resources :users
    get     'signup' => 'users#new'
    get     'login'  => 'sessions#new'
    post    'login'   => 'sessions#create'
    get    'logout'  => 'sessions#destroy'
    get   'profile'  => 'users#show'
   

end

app/models/cart.rb
class Cart < ActiveRecord::Base
    belongs_to :user
    has_many :line_items, dependent: :destroy
    def add_tour(tour_id)
        current_item = line_items.find_by_tour_id(tour_id)
        if current_item
            current_item.quantity += 1
        else
            current_item = line_items.build(tour_id: tour_id)
        end
        self.line_items << current_item
        current_item
    end

    def total_Price
    line_items.to_a.sum { |item| item.total_Price }
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [ :edit, :update, :destroy]
  

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  def current
    @cart = current_cart
    redirect_to action: 'show', id: @cart.id
  end
  
  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to destination_url, notice: 'Invalid cart'
      else
        respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    
    respond_to do |format|
      format.html { redirect_to destination_url,
      notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>

      <tr>
        <td><%= cart.created_at %></td>
        <td><%= cart.id %></td>

        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>


    <div class="cart_title">Your Cart</div>
    <table>
        <% @cart.line_items.each do |item| %>
        <tr>
            <td><%= item.quantity %>&times;</td>
            <td><%= item.tour.title %></td>
            <td class="item_price"><%= number_to_currency(item.total_Price) %></td>
        </tr>
    <% end %>
    <tr class="total_line">
        <td colspan="2">Total</td>
        <td class="total_cell"><%= number_to_currency(@cart.total_Price) %></td>
    </tr>
    </table>
    <%= button_to "Checkout", new_order_path, method: :get %>
    <%= button_to 'Empty cart', @cart, method: :delete, 
    confirm: 'Are you sure?' %>