config/routes.rb
Rails.application.routes.draw do
  
   root 'static_pages#home'
  resources :orders
  get 'store/index', as: 'destination'
  resources :store
  
    get 'carts/current' => 'carts#current', as: 'current'

  resources :line_items
  resources :carts
  resources :tours
 
  get   'about'   => 'static_pages#about'

  get   'contact' => 'static_pages#contact'

  get   'term'    => 'static_pages#term'

  get    'team'   => 'static_pages#team'

  get 'sessions/new'
 resources :users
    get     'signup' => 'users#new'
    get     'login'  => 'sessions#new'
    post    'login'   => 'sessions#create'
    get    'logout'  => 'sessions#destroy'
    get   'profile'  => 'users#show'
   

end

app/views/layouts/_footer.html.erb
<div id="footer">
  	
	  <div id="footer1">
		<h2>CONTACT</h2>
        <p>
		  <span class="boldtext">TEL:</span> +353 (1) 832 8167<br />
		  <span class="boldtext">FAX:</span> +353 (1) 832 8166<br />
		  <span class="boldtext">EMAIL:</span><a href="mailto:adventureholidays@gmail.com"> adventureholidays@gmail.com</a><br /><br /><br />
		  <a id="imagelink" href="http://ie.twitter.com/"><img src="assets/twitter.png" width="50" height="50" alt="Adventure Holidays Twitter"></a> &nbsp; 
          <a id="imagelink" href="http://www.facebook.com"><img src="assets/facebook.png" width="50" height="50" alt="Adventure Holidays Facebook" /></a> &nbsp  <br /><br /><br /><br />
	    </p>
		</div><!--footer1 closed-->
            
            <div id="footer2">
  			<h2>DESTINATIONS</h2>
			<p><ol>
		    <li><a href="asia.html">ASIA</a></li>
    		<li><a href="africa.html">AFRICA</a></li>
    		<li><a href="southamerica.html">SOUTH AMERICA</a></li>
    		<li><a href="europe.html">EUROPE</a></li>
		    </ol></p>         
			</div><!--footer2 closed-->
                      
            <div id="footer3">
  			<h2>USEFUL LINKS</h2>
			<ol>
		    <li><%= link_to "about",  about_path %></li>
    		<li><%= link_to "contact", contact_path %></li>
		    </ol>        
			</div><!--footer4 closed-->
            
            <div id="footer4">
  			<img src="assets/fadelogo.png" width="230" height="240" alt="logo">
			</div><!--footer4 closed-->
            
			</div><!--footer closed-->

			<div id="footerend">
            <h7>&nbsp;</h7>
            </div><!--footerend-->
            
</div><!--container closed-->

app/views/layouts/_header.html.erb
<div id="container">

	<div id="logo">
		<%= form_tag tours_path, :method => 'get' do %>
  		<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil %>
		</p>
	<% end %>
		
		 <% if logged_in? %>
		 <%= link_to '<button type="button">Update Profile</button>'.html_safe, edit_user_path(current_user) %>
		<%= link_to '<button type="button">Profile</button>'.html_safe, current_user %>
   		<%= link_to '<button type="button">Log out</button>'.html_safe, logout_path, method: "delete" %> 
   		 <% else %>
   		 <%= link_to '<button type="button">Login</button>'.html_safe, login_path %>
         <%= link_to '<button type="button">Signup Up</button>'.html_safe, signup_path %>
 		<% end %>
 		<%= link_to current_path do %>
  		<%= image_tag ("basketred.png") %> 
		<% end %>
   		
	</div>

<div id="menu">
	 <ul>
	 <li><%= link_to "Home", root_path %></li>

     <li><%= link_to "about",   about_path %></li>
     
	 <li><%= link_to "destination", destination_path %></li>
	 	<ul>
	 	<li><a href="asia.html">ASIA</a></li>
	 	<li><a href="africa.html">AFRICA</a></li>
	 	<li><a href="southamerica.html">SOUTH AMERICA</a></li>
        <li><a href="europe.html">EUROPE</a></li>
        </ul>

	  <li><%= link_to "contact", contact_path %></li>
	 </li>

    </ul>
    </div><!--menu closed-->  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title><%= yield(:title) %> | Adventure Holidays</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>
</head>

<body>
    
     <%= render 'layouts/header' %>    
    <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
     <%= debug(params) if Rails.env.development? %>
      <%= render 'layouts/footer' %>
    </div>
</body>
</html>